# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zcu104rev1.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zcu104_0_0/design_1_zcu104_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_zcu104_0_0 || ORIG_REF_NAME==design_1_zcu104_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_0/design_1_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps8_0_100M_0/design_1_rst_ps8_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps8_0_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zcu104_0_4/design_1_zcu104_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_zcu104_0_4 || ORIG_REF_NAME==design_1_zcu104_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zcu104_1_2/design_1_zcu104_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_zcu104_1_2 || ORIG_REF_NAME==design_1_zcu104_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zcu104_0_5/design_1_zcu104_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_zcu104_0_5 || ORIG_REF_NAME==design_1_zcu104_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zcu104_1_3/design_1_zcu104_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_zcu104_1_3 || ORIG_REF_NAME==design_1_zcu104_1_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zcu104_2_1/design_1_zcu104_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_zcu104_2_1 || ORIG_REF_NAME==design_1_zcu104_2_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zcu104_3_1/design_1_zcu104_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_zcu104_3_1 || ORIG_REF_NAME==design_1_zcu104_3_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zcu104_4_0/design_1_zcu104_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_zcu104_4_0 || ORIG_REF_NAME==design_1_zcu104_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zcu104_5_1/design_1_zcu104_5_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_zcu104_5_1 || ORIG_REF_NAME==design_1_zcu104_5_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_img_set_v1_0_0_0/design_1_img_set_v1_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_img_set_v1_0_0_0 || ORIG_REF_NAME==design_1_img_set_v1_0_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_contador_ciclos_0_0/design_1_contador_ciclos_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_contador_ciclos_0_0 || ORIG_REF_NAME==design_1_contador_ciclos_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
